### ISSUE TITLE
Delete unwanted `INSEE-` prefix for Lunatic questionnaire ID

### ISSUE THREAD

**Issue by romaintailhurat** [InseeFr/Eno#889]
For a given Pogues questionnaire ided with `abcde1234`, we use to have a Lunatic questionnaire with the same id.

Since Eno V3, this Lunatic id is now `INSEE-abcde1234`, but it is an _unwanted_ output, please provide the base id. 🙏

**Comment by nsenave** [comment]
The reason is that Eno Xml adds the `INSEE-` prefix in the Pogues to DDI transformation (only on the questionnaire's id).

No problem to remove this prefix in DDI to Lunatic transformation in Eno Java.

Now that we're talking about it, can't we remove this prefix also in the DDI? (Not necessarily right away but someday, e.g. when Pogues to DDI is rewritten in Eno Java.)
